services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'sw'
  wms:
    srs: ['EPSG:28356']
    image_formats: [image/png]
    md:
        title: Basemap
        online_resource: http://www.openstreetmap.org/
        contact:
            person: Alex Fraser
            organisation: VPAC Innovations
            email: alex@vpac-innovations.com.au

layers:
  - name: osm
    title: OpenStreetMap
    sources: [osm_cache]

caches:
  osm_cache:
    grids: [primary]
    sources: [osm_local]

sources:
  osm_local:
    type: mapnik
    mapfile: /var/lib/basemap/style/basemap.xml

grids:
    primary:
        srs: EPSG:28356
        bbox: [220000, 6190000, 380000, 6350000]
        res: [2560.0, 1280.0, 640.0, 320.0, 160.0, 80.0, 40.0, 20.0, 10.0, 5.0,
              2.5, 1.25, 0.625, 0.3125]

globals:
    cache:
        base_dir: /var/lib/basemap/cache/
